title: INOG
description: INOG is Not Only Geeks
author: INOG
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/ashutosh2k12
about: INOG is Not Only Geeks

baseurl: "https://szuinog.github.io"
url: "https://szuinog.github.io"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
